cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "telemachus/brew", "https://telemachus@bitbucket.org/telemachus/brew.git", pin: true
tap "caskroom/fonts"

brew "bat"
brew "diff-so-fancy"
brew "dust"
brew "exa"
brew "fasd"
brew "fd"
brew "fzf"
brew "git"
brew "git-extras"
brew "htop"
brew "jq"
brew "mas"
brew "mdcat"
brew "neovim"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "watch"
brew "wget"
brew "zsh"
brew "zplug"

cask "alfred"
cask "docker"
cask "caskroom/fonts/font-firacode-nerd-font"
cask "caskroom/fonts/font-victor-mono"
cask "google-chrome"
cask "iterm2"
cask "kindle"
cask "notion"
cask "station"
cask "spotify"

mas "1Password", id: 1333542190
mas "Spark", id: 1176895641
mas "Magnet", id: 441258766

brew "awscli"
brew "terraform"
brew "terragrunt"
cask "google-cloud-sdk"
cask "miro-formerly-realtimeboard"
cask "vagrant"
