-- local packer_path = U.os.data .. "/site/pack/packer/opt/packer.nvim"
-- if vim.fn.empty(vim.fn.glob(packer_path)) > 0 then
-- 	vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. packer_path)
-- end
-- vim.cmd("packadd packer.nvim | au BufWritePost plugins.lua PackerCompile")
-- vim.opt.rtp = vim.opt.rtp + (U.os.data .. "/site/pack/packer/opt/*")
--
-- local packer = require("packer")
-- local plugin_path = U.os.data .. "/site/pack/packer/opt/"
-- local packer_compiled = U.os.data .. "/site/plugin/packer_compiled.vim"
--
-- return packer.startup(function(use)
-- 	packer.init({ compile_path = packer_compiled, opt_default = true })
--
-- 	use({ "phaazon/hop.nvim", setup = [[require('plugin.hop')]] })
-- 	use("tpope/vim-repeat")
-- 	use("tpope/vim-surround")
-- 	use("wellle/targets.vim")
--
-- 	-- Autoinstall/compile plugins
-- 	if vim.fn.isdirectory(vim.fn.glob(plugin_path)) > 0 then
-- 		packer.install()
-- 	end
-- 	if vim.fn.empty(vim.fn.glob(packer_compiled)) > 0 then
-- 		packer.compile()
-- 	end
-- end)
