let g:coc_global_extensions = [
	\"coc-syntax",
	\"coc-emoji",
	\"coc-json",
	\"coc-tsserver",
	\"coc-yaml",
	\"coc-highlight",
	\"coc-snippets",
	\"coc-marketplace",
	\"coc-eslint",
	\"coc-css",
	\"coc-prettier",
	\"coc-git",
	\"coc-html",
	\"coc-pairs"]
